Repository Gogeloo/efficiency-6, pull requests merged in 2024-06, with the labels that each got.

#2 fix: modify get_active_computer import
  app/api/api.py
  app/main.py
Labels: bug

#5 Update malformed uvicorn version.
  pyproject.toml
Labels: bug

#3 Add raw file support
  .env.example
  .vscode/settings.json
  app/api/api.py
  app/api/endpoints/computer_information/get_active_computer.py
  app/api/endpoints/lua/list_files.py
  app/api/endpoints/lua/lua_file.py
  app/api/models/detailed_error_response.py
  app/api/models/error_response.py
  app/api/models/file_list_response.py
  app/api/models/file_response.py
  app/main.py
  app/settings.py
  lua_files/test.lua
  lua_files/test_folder/test2.lua
Labels: enhancement

#1 docs: update endpoint structure
  .vscode/settings.json
  structure.md
Labels: documentation

#11 fix: Modify settings import
  app/api/endpoints/lua/post_lua_file.py
Labels: bug
